# ------------------------ Even Fibonacci numbers ----------------------------- #
#                                                                               #
#   Each new term in the Fibonacci sequence is generated by adding the          #
#   previous two terms. By starting with 1 and 2, the first 10 terms will be:   #
#               1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...                          #
#                                                                               #
#   By considering the terms in the Fibonacci sequence whose values do not      #
#   exceed four million, find the sum of the even-valued terms.                 #
#   we get 3, 5, 6 and 9. The sum of these multiples is 23.                     #
# ----------------------------------------------------------------------------- #
import profile
import time

MAX = 4000000

def main():
    lastFib = 1
    newFib  = 2
    sumOfEvenFibTerms     = 0

    while (newFib <= MAX):
        if (newFib % 2 == 0):
            sumOfEvenFibTerms += newFib
        newFib += lastFib
        lastFib = newFib - lastFib
    
    return (sumOfEvenFibTerms)

startTime = time.clock() 
profile.run("print (main())")
elapsedTime = time.clock() - startTime
print ("Time spent in (function name) is: ", elapsedTime, " sec")
